Update workflows

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -83,7 +83,10 @@ jobs:
       - name: 'Get result'
         id: get-result
         run: |
-          echo 'TRIGGERED ${{ failure() && (needs.deploy.result != 'failure' || (needs.deploy.result == 'failure' && needs.deploy.outputs.TRIGGERED == 'true')) }}'
+#          echo 'TRIGGERED ${{ failure() && (needs.deploy.result != 'failure' || (needs.deploy.result == 'failure' && needs.deploy.outputs.TRIGGERED == 'true')) }}'
+          echo 'needs.deploy.result=${{ needs.deploy.result }}'
+          echo 'needs.deploy.outputs.TRIGGERED=${{ needs.deploy.outputs.TRIGGERED }}'
+          echo 'needs.deploy.outputs.TRIGGERED_true=${{ needs.deploy.outputs.TRIGGERED == 'true' }}'
           echo 'TRIGGERED=${{ needs.deploy.outputs.TRIGGERED }}'
           echo 'RESULT=${{ needs.deploy.result }}'
           echo 'CONCLUSION=${{ needs.deploy.conclusion }}'
